### ISSUE TITLE
Generated error from missing dependencies

### ISSUE THREAD

**Issue by Pitcheyh** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#12]
### How are you playing the game?

Single Player - No Server

### What happened?

Following error is generated in BepInEx log when booting the game.

"Could not load [Digitalroot Valheim EpicLoot Adventure Bounties for Epic Valheim 1.0.3] because it has missing dependencies: DYBAssets"

### To Reproduce

Booting the game

### Screenshots

![image](https://user-images.githubusercontent.com/90159800/132143567-68f26455-d0c4-4a8f-a411-7742a2fe028e.png)

### Relevant log output

```shell
[Error  :   BepInEx] Could not load [Digitalroot Valheim EpicLoot Adventure Bounties for Epic Valheim 1.0.3] because it has missing dependencies: DYBAssets
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Please follow the install instructions for [Epic Valheim 3.1](https://www.nexusmods.com/valheim/mods/1409). 

That error is because you are missing the [MonsterLabZ](https://www.nexusmods.com/valheim/mods/1264) mod.

If you are not trying to use the Epic Valheim 3.1 setup, then remove Digitalroot.EpicLoot.Bounties.EpicValheim.dll as it is only used for Epic Valheim 3.1

**Comment by Pitcheyh** [comment]
Thanks for your prompt help
