### ISSUE TITLE
[Bug]: Not Loading from D.Server

### ISSUE THREAD

**Issue by Digitalroot** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#13]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

New bounties are not showing up when playing on a DS. 

### To Reproduce

Add mods to server and client. 
Config for sever sync.
Connect to DS.
Visit Trader
Mods missing

### Screenshots

![image](https://user-images.githubusercontent.com/3770289/132560267-860c0922-a4ca-4ad6-b6c4-7a8c65548227.png)

### Log File

[Client-LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/7130913/Client-LogOutput.log)
[Server-LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/7130914/Server-LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mercillern128** [comment]
Having this issue when playing on my windows dedicated server. The mod works without issues in singleplayer on the client using the same mod list.
Here's an additional log file where the debug output seemingly adds the bounties, but alas has no effect in game.
[LogOutput (4).log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/7131034/LogOutput.4.log)

**Comment by swolewizard** [comment]
I'm also having this issue on a dedicated server, I thought it was something with having to unlock keys and discovering deep north/mistlands/ashlands which is why I wasn't getting any bounties in those areas, this is why I didn't report it, but we've recently progressed enough and discovered all biomes and killed all vanilla bosses and have even killed epic valheims T6 boss in the mistlands, still not receiving any deepnorth/mistlands/ashlands bounties.

but on a singleplayer world with the same progress I am able to get most've my bounties to spawn in the ocean/mistlands/ashlands/deepnorth and they give golden tokens rather than on the dedicated server they all give iron tokens.

**On multiplayer world.**
![44](https://user-images.githubusercontent.com/46814896/132715777-327aaf84-c104-4815-bb3d-006e4068db00.PNG)

**Exactly same world, but loaded on singleplayer.**
![45](https://user-images.githubusercontent.com/46814896/132716317-b54369dc-b5e1-4ed2-b0ea-1817f55133a2.PNG)

**Comment by Digitalroot** [comment]
I think there is a problem in how I hook into it for DS. I am trying a new load method and will release it if it fixes the issue.

**Comment by Digitalroot** [comment]
Ref https://forums.nexusmods.com/index.php?/topic/10310938-epic-valheim-v30-gameplay-expander-using-most-popular-mods/page-22

**Comment by Digitalroot** [comment]
This is taking longer to fix then expected. I didn't test enough before on a DS and keep finding issues.

**Comment by minc727** [comment]
I've had this issue as well - originally it looked like that the client would load the bounties correctly, but when connecting to the DS the server would sync the adventuredata.json and overwrite the bounties (even when the config lock option was disabled).  I ended up patching the EpicLoot.dll file to disable the client / server sync entirely (by putting a return as the first statement in ServerSync.RPC_ConfigSync) which fixed the problem.  The new update seems to work, but if the server side adventuredata.json file is edited while a user is connected, the server will still replace the client's bounties with the ones from the server (even if the bounty section isn't present in the adventuredata.json file). This happens both if the Digitalroot adventure dlls (base + epicvalheim one) are installed on the server or not.

**Comment by Digitalroot** [comment]
Good info.
